GET http://localhost:3000/users/all

################################

DELETE http://localhost:3000/users/delete

Content-Type: application/x-www-form-urlencoded

{
    id:"0b6eaadb-649d-44cc-a2e8-5218c9c8797d"
}